name: Rust

on:
  push:
    branches: [ main, feature/*, release/* ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            target-name: win32-x64
            exe-name: target/release/moos-ivp-language-server.exe
          - os: windows-latest
            target: i686-pc-windows-msvc
            target-name: win32-i686
            exe-name: target/release/moos-ivp-language-server.exe
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            target-name: linux-x64
            exe-name: target/release/moos-ivp-language-server
          - os: macos-12
            target: x86_64-apple-darwin
            target-name: darwin-x64
            exe-name: target/release/moos-ivp-language-server
          - os: macos-12
            target: aarch64-apple-darwin
            target-name: darwin-arm64
            exe-name: target/release/moos-ivp-language-server

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repostiory
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload Language Server
      uses: actions/upload-artifact@v4
      with:
        name: moos-ivp-language-server-${{ matrix.target-name }}.zip
        path: |
          ${{ matrix.exe-name }}
          !target/release/moos-ivp-language-server.d
        compression-level: 9
        if-no-files-found: error
    - name: Setup VS Code Extension
      run: cp ${{ matrix.exe-name }} editors/vscode/server/
    - name: Build VS Code Extension
      run: npm install && npm run compile
      working-directory: editors/vscode
    - name: Package VS Code Extension
      run: npx @vscode/vsce package --out moos-ivp-editor-${{ matrix.target-name }}.vsix
      working-directory: editors/vscode
    - name: Upload VS Code Extension
      uses: actions/upload-artifact@v4
      with:
        name: moos-ivp-editor-${{ matrix.target-name }}.vsix
        path: editors/vscode/moos-ivp-editor-${{ matrix.target-name }}.vsix
        compression-level: 0
        if-no-files-found: error
