name: Rust

on:
  push:
    branches: [ main, feature/*, release/* ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: moos-ivp-language-server-${{ matrix.os }}.zip
        path: |
          target/release/moos-ivp-language-server*
          !target/release/moos-ivp-language-server.d
        compression-level: 9
        if-no-files-found: error