name: Rust

on:
  push:
    branches: [ main, feature/*, release/* ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            target-name: win32-x64
          - os: windows-latest
            target: i686-pc-windows-msvc
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            target-name: linux-x64
          - os: macos-12
            target: x86_64-apple-darwin
            target-name: darwin-x64
          - os: macos-12
            target: aarch64-apple-darwin
            target-name: darwin-arm64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: moos-ivp-language-server-${{ matrix.target-name }}.zip
        path: |
          target/release/moos-ivp-language-server*
          !target/release/moos-ivp-language-server.d
        compression-level: 9
        if-no-files-found: error
    - name: Setup VS Code Extension
      run: cp target/release/moos-ivp-language-server editors/vscode/server/